name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: Username
          POSTGRES_PASSWORD: your_password
          POSTGRES_DB: budgy_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U Username"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2

      - name: Run database setup
        run: |
          bin/rails db:create db:migrate
        env:
          DATABASE_HOST: localhost
          DATABASE_USERNAME: Username
          DATABASE_PASSWORD: your_password

      - name: Run tests
        run: bundle exec rake test || echo "No tests found"

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          IMAGE_NAME=fadysaad66/budgetapp
          IMAGE_TAG=latest
          docker build -t $IMAGE_NAME:$IMAGE_TAG .
          docker push $IMAGE_NAME:$IMAGE_TAG
